
import { Inter } from 'next/font/google'
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from '@/providers/contexts/theme-context';
import { ThemeScript } from '@/components/theme-script'

export const metadata: Metadata = {
  title: "Evenzia - Event Management Platform",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}